# Backend Deployment for EKS with ECR images
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: evchargershare
  labels:
    app: backend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      initContainers:
      - name: wait-for-mongodb
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z mongodb-service 27017; do echo "Waiting for MongoDB..."; sleep 5; done; echo "MongoDB is ready!"']
      - name: wait-for-redis
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z redis-service 6379; do echo "Waiting for Redis..."; sleep 5; done; echo "Redis is ready!"']
      containers:
      - name: backend
        image: evchargershare-backend:latest  # This will be replaced by deployment script
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PORT
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_URI
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_URL
        - name: CLIENT_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: CLIENT_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_REFRESH_SECRET
        - name: JWT_EXPIRE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: JWT_EXPIRE
        - name: JWT_REFRESH_EXPIRE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: JWT_REFRESH_EXPIRE
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: STRIPE_SECRET_KEY
        - name: STRIPE_PUBLISHABLE_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: STRIPE_PUBLISHABLE_KEY
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AWS_REGION
        - name: AWS_S3_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AWS_S3_BUCKET_NAME
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: EMAIL_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: EMAIL_HOST
        - name: EMAIL_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: EMAIL_PORT
        - name: EMAIL_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: EMAIL_USER
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: EMAIL_PASSWORD
        - name: EMAIL_FROM
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: EMAIL_FROM
        - name: OPENCAGE_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENCAGE_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 1000

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: evchargershare
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: backend

---
# Horizontal Pod Autoscaler for Backend
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: evchargershare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
